---
- 
  hosts: all
  become: true
  tasks:

    - name: "For install apache server"
      apt:
        update_cache: yes
        upgrade: yes

    - name: "install apache"
      apt:
        name: apache2
        state: present
